package seeder

import (
	"location-service/internal/models"
)

func getCountriesData() []models.Country {
	// Helper function for pointer conversion
	float64Ptr := func(f float64) *float64 { return &f }

	return []models.Country{
		{
			ID:          "US",
			Name:        "United States",
			NativeName:  "United States",
			Capital:     "Washington",
			Region:      "Americas",
			Subregion:   "Northern America",
			Currency:    "USD",
			Languages:   `["en"]`,
			CallingCode: "+1",
			FlagEmoji:   "🇺🇸",
			Latitude:    float64Ptr(37.0902),
			Longitude:   float64Ptr(-95.7129),
			Active:      true,
		},
		{
			ID:          "CA",
			Name:        "Canada",
			NativeName:  "Canada",
			Capital:     "Ottawa",
			Region:      "Americas",
			Subregion:   "Northern America",
			Currency:    "CAD",
			Languages:   `["en","fr"]`,
			CallingCode: "+1",
			FlagEmoji:   "🇨🇦",
			Latitude:    float64Ptr(56.1304),
			Longitude:   float64Ptr(-106.3468),
			Active:      true,
		},
		{
			ID:          "GB",
			Name:        "United Kingdom",
			NativeName:  "United Kingdom",
			Capital:     "London",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "GBP",
			Languages:   `["en"]`,
			CallingCode: "+44",
			FlagEmoji:   "🇬🇧",
			Latitude:    float64Ptr(55.3781),
			Longitude:   float64Ptr(-3.4360),
			Active:      true,
		},
		{
			ID:          "IN",
			Name:        "India",
			NativeName:  "भारत",
			Capital:     "New Delhi",
			Region:      "Asia",
			Subregion:   "Southern Asia",
			Currency:    "INR",
			Languages:   `["hi","en"]`,
			CallingCode: "+91",
			FlagEmoji:   "🇮🇳",
			Latitude:    float64Ptr(20.5937),
			Longitude:   float64Ptr(78.9629),
			Active:      true,
		},
		{
			ID:          "AU",
			Name:        "Australia",
			NativeName:  "Australia",
			Capital:     "Canberra",
			Region:      "Oceania",
			Subregion:   "Australia and New Zealand",
			Currency:    "AUD",
			Languages:   `["en"]`,
			CallingCode: "+61",
			FlagEmoji:   "🇦🇺",
			Latitude:    float64Ptr(-25.2744),
			Longitude:   float64Ptr(133.7751),
			Active:      true,
		},
		{
			ID:          "DE",
			Name:        "Germany",
			NativeName:  "Deutschland",
			Capital:     "Berlin",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "EUR",
			Languages:   `["de"]`,
			CallingCode: "+49",
			FlagEmoji:   "🇩🇪",
			Latitude:    float64Ptr(51.1657),
			Longitude:   float64Ptr(10.4515),
			Active:      true,
		},
		{
			ID:          "FR",
			Name:        "France",
			NativeName:  "France",
			Capital:     "Paris",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "EUR",
			Languages:   `["fr"]`,
			CallingCode: "+33",
			FlagEmoji:   "🇫🇷",
			Latitude:    float64Ptr(46.2276),
			Longitude:   float64Ptr(2.2137),
			Active:      true,
		},
		{
			ID:          "JP",
			Name:        "Japan",
			NativeName:  "日本",
			Capital:     "Tokyo",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "JPY",
			Languages:   `["ja"]`,
			CallingCode: "+81",
			FlagEmoji:   "🇯🇵",
			Latitude:    float64Ptr(36.2048),
			Longitude:   float64Ptr(138.2529),
			Active:      true,
		},
		{
			ID:          "CN",
			Name:        "China",
			NativeName:  "中国",
			Capital:     "Beijing",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "CNY",
			Languages:   `["zh"]`,
			CallingCode: "+86",
			FlagEmoji:   "🇨🇳",
			Latitude:    float64Ptr(35.8617),
			Longitude:   float64Ptr(104.1954),
			Active:      true,
		},
		{
			ID:          "BR",
			Name:        "Brazil",
			NativeName:  "Brasil",
			Capital:     "Brasília",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "BRL",
			Languages:   `["pt"]`,
			CallingCode: "+55",
			FlagEmoji:   "🇧🇷",
			Latitude:    float64Ptr(-14.2350),
			Longitude:   float64Ptr(-51.9253),
			Active:      true,
		},
		{
			ID:          "MX",
			Name:        "Mexico",
			NativeName:  "México",
			Capital:     "Mexico City",
			Region:      "Americas",
			Subregion:   "Central America",
			Currency:    "MXN",
			Languages:   `["es"]`,
			CallingCode: "+52",
			FlagEmoji:   "🇲🇽",
			Latitude:    float64Ptr(23.6345),
			Longitude:   float64Ptr(-102.5528),
			Active:      true,
		},
		{
			ID:          "IT",
			Name:        "Italy",
			NativeName:  "Italia",
			Capital:     "Rome",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "EUR",
			Languages:   `["it"]`,
			CallingCode: "+39",
			FlagEmoji:   "🇮🇹",
			Latitude:    float64Ptr(41.8719),
			Longitude:   float64Ptr(12.5674),
			Active:      true,
		},
		{
			ID:          "ES",
			Name:        "Spain",
			NativeName:  "España",
			Capital:     "Madrid",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "EUR",
			Languages:   `["es"]`,
			CallingCode: "+34",
			FlagEmoji:   "🇪🇸",
			Latitude:    float64Ptr(40.4637),
			Longitude:   float64Ptr(-3.7492),
			Active:      true,
		},
		{
			ID:          "NL",
			Name:        "Netherlands",
			NativeName:  "Nederland",
			Capital:     "Amsterdam",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "EUR",
			Languages:   `["nl"]`,
			CallingCode: "+31",
			FlagEmoji:   "🇳🇱",
			Latitude:    float64Ptr(52.1326),
			Longitude:   float64Ptr(5.2913),
			Active:      true,
		},
		{
			ID:          "SE",
			Name:        "Sweden",
			NativeName:  "Sverige",
			Capital:     "Stockholm",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "SEK",
			Languages:   `["sv"]`,
			CallingCode: "+46",
			FlagEmoji:   "🇸🇪",
			Latitude:    float64Ptr(60.1282),
			Longitude:   float64Ptr(18.6435),
			Active:      true,
		},
		{
			ID:          "SG",
			Name:        "Singapore",
			NativeName:  "Singapore",
			Capital:     "Singapore",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "SGD",
			Languages:   `["en","ms","zh","ta"]`,
			CallingCode: "+65",
			FlagEmoji:   "🇸🇬",
			Latitude:    float64Ptr(1.3521),
			Longitude:   float64Ptr(103.8198),
			Active:      true,
		},
		{
			ID:          "NZ",
			Name:        "New Zealand",
			NativeName:  "New Zealand",
			Capital:     "Wellington",
			Region:      "Oceania",
			Subregion:   "Australia and New Zealand",
			Currency:    "NZD",
			Languages:   `["en","mi"]`,
			CallingCode: "+64",
			FlagEmoji:   "🇳🇿",
			Latitude:    float64Ptr(-40.9006),
			Longitude:   float64Ptr(174.8860),
			Active:      true,
		},
		{
			ID:          "ZA",
			Name:        "South Africa",
			NativeName:  "South Africa",
			Capital:     "Pretoria",
			Region:      "Africa",
			Subregion:   "Southern Africa",
			Currency:    "ZAR",
			Languages:   `["en","af","zu","xh"]`,
			CallingCode: "+27",
			FlagEmoji:   "🇿🇦",
			Latitude:    float64Ptr(-30.5595),
			Longitude:   float64Ptr(22.9375),
			Active:      true,
		},
		{
			ID:          "AE",
			Name:        "United Arab Emirates",
			NativeName:  "الإمارات العربية المتحدة",
			Capital:     "Abu Dhabi",
			Region:      "Asia",
			Subregion:   "Western Asia",
			Currency:    "AED",
			Languages:   `["ar"]`,
			CallingCode: "+971",
			FlagEmoji:   "🇦🇪",
			Latitude:    float64Ptr(23.4241),
			Longitude:   float64Ptr(53.8478),
			Active:      true,
		},
		{
			ID:          "KR",
			Name:        "South Korea",
			NativeName:  "대한민국",
			Capital:     "Seoul",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "KRW",
			Languages:   `["ko"]`,
			CallingCode: "+82",
			FlagEmoji:   "🇰🇷",
			Latitude:    float64Ptr(35.9078),
			Longitude:   float64Ptr(127.7669),
			Active:      true,
		},
	}
}
