package seeder

import (
	"location-service/internal/models"
)

func getCountriesData() []models.Country {
	// Helper function for pointer conversion
	float64Ptr := func(f float64) *float64 { return &f }

	return []models.Country{
		{
			ID:          "US",
			Name:        "United States",
			NativeName:  "United States",
			Capital:     "Washington",
			Region:      "Americas",
			Subregion:   "Northern America",
			Currency:    "USD",
			Languages:   `["en"]`,
			CallingCode: "+1",
			FlagEmoji:   "🇺🇸",
			Latitude:    float64Ptr(37.0902),
			Longitude:   float64Ptr(-95.7129),
			Active:      true,
		},
		{
			ID:          "CA",
			Name:        "Canada",
			NativeName:  "Canada",
			Capital:     "Ottawa",
			Region:      "Americas",
			Subregion:   "Northern America",
			Currency:    "CAD",
			Languages:   `["en","fr"]`,
			CallingCode: "+1",
			FlagEmoji:   "🇨🇦",
			Latitude:    float64Ptr(56.1304),
			Longitude:   float64Ptr(-106.3468),
			Active:      true,
		},
		{
			ID:          "GB",
			Name:        "United Kingdom",
			NativeName:  "United Kingdom",
			Capital:     "London",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "GBP",
			Languages:   `["en"]`,
			CallingCode: "+44",
			FlagEmoji:   "🇬🇧",
			Latitude:    float64Ptr(55.3781),
			Longitude:   float64Ptr(-3.4360),
			Active:      true,
		},
		{
			ID:          "IN",
			Name:        "India",
			NativeName:  "भारत",
			Capital:     "New Delhi",
			Region:      "Asia",
			Subregion:   "Southern Asia",
			Currency:    "INR",
			Languages:   `["hi","en"]`,
			CallingCode: "+91",
			FlagEmoji:   "🇮🇳",
			Latitude:    float64Ptr(20.5937),
			Longitude:   float64Ptr(78.9629),
			Active:      true,
		},
		{
			ID:          "AU",
			Name:        "Australia",
			NativeName:  "Australia",
			Capital:     "Canberra",
			Region:      "Oceania",
			Subregion:   "Australia and New Zealand",
			Currency:    "AUD",
			Languages:   `["en"]`,
			CallingCode: "+61",
			FlagEmoji:   "🇦🇺",
			Latitude:    float64Ptr(-25.2744),
			Longitude:   float64Ptr(133.7751),
			Active:      true,
		},
		{
			ID:          "DE",
			Name:        "Germany",
			NativeName:  "Deutschland",
			Capital:     "Berlin",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "EUR",
			Languages:   `["de"]`,
			CallingCode: "+49",
			FlagEmoji:   "🇩🇪",
			Latitude:    float64Ptr(51.1657),
			Longitude:   float64Ptr(10.4515),
			Active:      true,
		},
		{
			ID:          "FR",
			Name:        "France",
			NativeName:  "France",
			Capital:     "Paris",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "EUR",
			Languages:   `["fr"]`,
			CallingCode: "+33",
			FlagEmoji:   "🇫🇷",
			Latitude:    float64Ptr(46.2276),
			Longitude:   float64Ptr(2.2137),
			Active:      true,
		},
		{
			ID:          "JP",
			Name:        "Japan",
			NativeName:  "日本",
			Capital:     "Tokyo",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "JPY",
			Languages:   `["ja"]`,
			CallingCode: "+81",
			FlagEmoji:   "🇯🇵",
			Latitude:    float64Ptr(36.2048),
			Longitude:   float64Ptr(138.2529),
			Active:      true,
		},
		{
			ID:          "CN",
			Name:        "China",
			NativeName:  "中国",
			Capital:     "Beijing",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "CNY",
			Languages:   `["zh"]`,
			CallingCode: "+86",
			FlagEmoji:   "🇨🇳",
			Latitude:    float64Ptr(35.8617),
			Longitude:   float64Ptr(104.1954),
			Active:      true,
		},
		{
			ID:          "BR",
			Name:        "Brazil",
			NativeName:  "Brasil",
			Capital:     "Brasília",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "BRL",
			Languages:   `["pt"]`,
			CallingCode: "+55",
			FlagEmoji:   "🇧🇷",
			Latitude:    float64Ptr(-14.2350),
			Longitude:   float64Ptr(-51.9253),
			Active:      true,
		},
		{
			ID:          "MX",
			Name:        "Mexico",
			NativeName:  "México",
			Capital:     "Mexico City",
			Region:      "Americas",
			Subregion:   "Central America",
			Currency:    "MXN",
			Languages:   `["es"]`,
			CallingCode: "+52",
			FlagEmoji:   "🇲🇽",
			Latitude:    float64Ptr(23.6345),
			Longitude:   float64Ptr(-102.5528),
			Active:      true,
		},
		{
			ID:          "IT",
			Name:        "Italy",
			NativeName:  "Italia",
			Capital:     "Rome",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "EUR",
			Languages:   `["it"]`,
			CallingCode: "+39",
			FlagEmoji:   "🇮🇹",
			Latitude:    float64Ptr(41.8719),
			Longitude:   float64Ptr(12.5674),
			Active:      true,
		},
		{
			ID:          "ES",
			Name:        "Spain",
			NativeName:  "España",
			Capital:     "Madrid",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "EUR",
			Languages:   `["es"]`,
			CallingCode: "+34",
			FlagEmoji:   "🇪🇸",
			Latitude:    float64Ptr(40.4637),
			Longitude:   float64Ptr(-3.7492),
			Active:      true,
		},
		{
			ID:          "NL",
			Name:        "Netherlands",
			NativeName:  "Nederland",
			Capital:     "Amsterdam",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "EUR",
			Languages:   `["nl"]`,
			CallingCode: "+31",
			FlagEmoji:   "🇳🇱",
			Latitude:    float64Ptr(52.1326),
			Longitude:   float64Ptr(5.2913),
			Active:      true,
		},
		{
			ID:          "SE",
			Name:        "Sweden",
			NativeName:  "Sverige",
			Capital:     "Stockholm",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "SEK",
			Languages:   `["sv"]`,
			CallingCode: "+46",
			FlagEmoji:   "🇸🇪",
			Latitude:    float64Ptr(60.1282),
			Longitude:   float64Ptr(18.6435),
			Active:      true,
		},
		{
			ID:          "SG",
			Name:        "Singapore",
			NativeName:  "Singapore",
			Capital:     "Singapore",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "SGD",
			Languages:   `["en","ms","zh","ta"]`,
			CallingCode: "+65",
			FlagEmoji:   "🇸🇬",
			Latitude:    float64Ptr(1.3521),
			Longitude:   float64Ptr(103.8198),
			Active:      true,
		},
		{
			ID:          "NZ",
			Name:        "New Zealand",
			NativeName:  "New Zealand",
			Capital:     "Wellington",
			Region:      "Oceania",
			Subregion:   "Australia and New Zealand",
			Currency:    "NZD",
			Languages:   `["en","mi"]`,
			CallingCode: "+64",
			FlagEmoji:   "🇳🇿",
			Latitude:    float64Ptr(-40.9006),
			Longitude:   float64Ptr(174.8860),
			Active:      true,
		},
		{
			ID:          "ZA",
			Name:        "South Africa",
			NativeName:  "South Africa",
			Capital:     "Pretoria",
			Region:      "Africa",
			Subregion:   "Southern Africa",
			Currency:    "ZAR",
			Languages:   `["en","af","zu","xh"]`,
			CallingCode: "+27",
			FlagEmoji:   "🇿🇦",
			Latitude:    float64Ptr(-30.5595),
			Longitude:   float64Ptr(22.9375),
			Active:      true,
		},
		{
			ID:          "AE",
			Name:        "United Arab Emirates",
			NativeName:  "الإمارات العربية المتحدة",
			Capital:     "Abu Dhabi",
			Region:      "Asia",
			Subregion:   "Western Asia",
			Currency:    "AED",
			Languages:   `["ar"]`,
			CallingCode: "+971",
			FlagEmoji:   "🇦🇪",
			Latitude:    float64Ptr(23.4241),
			Longitude:   float64Ptr(53.8478),
			Active:      true,
		},
		{
			ID:          "KR",
			Name:        "South Korea",
			NativeName:  "대한민국",
			Capital:     "Seoul",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "KRW",
			Languages:   `["ko"]`,
			CallingCode: "+82",
			FlagEmoji:   "🇰🇷",
			Latitude:    float64Ptr(35.9078),
			Longitude:   float64Ptr(127.7669),
			Active:      true,
		},
		// South Asian Countries
		{
			ID:          "NP",
			Name:        "Nepal",
			NativeName:  "नेपाल",
			Capital:     "Kathmandu",
			Region:      "Asia",
			Subregion:   "Southern Asia",
			Currency:    "NPR",
			Languages:   `["ne"]`,
			CallingCode: "+977",
			FlagEmoji:   "🇳🇵",
			Latitude:    float64Ptr(28.3949),
			Longitude:   float64Ptr(84.1240),
			Active:      true,
		},
		{
			ID:          "BD",
			Name:        "Bangladesh",
			NativeName:  "বাংলাদেশ",
			Capital:     "Dhaka",
			Region:      "Asia",
			Subregion:   "Southern Asia",
			Currency:    "BDT",
			Languages:   `["bn"]`,
			CallingCode: "+880",
			FlagEmoji:   "🇧🇩",
			Latitude:    float64Ptr(23.6850),
			Longitude:   float64Ptr(90.3563),
			Active:      true,
		},
		{
			ID:          "LK",
			Name:        "Sri Lanka",
			NativeName:  "ශ්‍රී ලංකාව",
			Capital:     "Sri Jayawardenepura Kotte",
			Region:      "Asia",
			Subregion:   "Southern Asia",
			Currency:    "LKR",
			Languages:   `["si","ta"]`,
			CallingCode: "+94",
			FlagEmoji:   "🇱🇰",
			Latitude:    float64Ptr(7.8731),
			Longitude:   float64Ptr(80.7718),
			Active:      true,
		},
		{
			ID:          "PK",
			Name:        "Pakistan",
			NativeName:  "پاکستان",
			Capital:     "Islamabad",
			Region:      "Asia",
			Subregion:   "Southern Asia",
			Currency:    "PKR",
			Languages:   `["ur","en"]`,
			CallingCode: "+92",
			FlagEmoji:   "🇵🇰",
			Latitude:    float64Ptr(30.3753),
			Longitude:   float64Ptr(69.3451),
			Active:      true,
		},
		{
			ID:          "AF",
			Name:        "Afghanistan",
			NativeName:  "افغانستان",
			Capital:     "Kabul",
			Region:      "Asia",
			Subregion:   "Southern Asia",
			Currency:    "AFN",
			Languages:   `["ps","uz","tk"]`,
			CallingCode: "+93",
			FlagEmoji:   "🇦🇫",
			Latitude:    float64Ptr(33.9391),
			Longitude:   float64Ptr(67.7100),
			Active:      true,
		},
		{
			ID:          "BT",
			Name:        "Bhutan",
			NativeName:  "འབྲུག",
			Capital:     "Thimphu",
			Region:      "Asia",
			Subregion:   "Southern Asia",
			Currency:    "BTN",
			Languages:   `["dz"]`,
			CallingCode: "+975",
			FlagEmoji:   "🇧🇹",
			Latitude:    float64Ptr(27.5142),
			Longitude:   float64Ptr(90.4336),
			Active:      true,
		},
		{
			ID:          "MV",
			Name:        "Maldives",
			NativeName:  "ދިވެހިރާއްޖެ",
			Capital:     "Malé",
			Region:      "Asia",
			Subregion:   "Southern Asia",
			Currency:    "MVR",
			Languages:   `["dv"]`,
			CallingCode: "+960",
			FlagEmoji:   "🇲🇻",
			Latitude:    float64Ptr(3.2028),
			Longitude:   float64Ptr(73.2207),
			Active:      true,
		},
		// Southeast Asian Countries
		{
			ID:          "ID",
			Name:        "Indonesia",
			NativeName:  "Indonesia",
			Capital:     "Jakarta",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "IDR",
			Languages:   `["id"]`,
			CallingCode: "+62",
			FlagEmoji:   "🇮🇩",
			Latitude:    float64Ptr(-0.7893),
			Longitude:   float64Ptr(113.9213),
			Active:      true,
		},
		{
			ID:          "PH",
			Name:        "Philippines",
			NativeName:  "Pilipinas",
			Capital:     "Manila",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "PHP",
			Languages:   `["tl","en"]`,
			CallingCode: "+63",
			FlagEmoji:   "🇵🇭",
			Latitude:    float64Ptr(12.8797),
			Longitude:   float64Ptr(121.7740),
			Active:      true,
		},
		{
			ID:          "TH",
			Name:        "Thailand",
			NativeName:  "ประเทศไทย",
			Capital:     "Bangkok",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "THB",
			Languages:   `["th"]`,
			CallingCode: "+66",
			FlagEmoji:   "🇹🇭",
			Latitude:    float64Ptr(15.8700),
			Longitude:   float64Ptr(100.9925),
			Active:      true,
		},
		{
			ID:          "VN",
			Name:        "Vietnam",
			NativeName:  "Việt Nam",
			Capital:     "Hanoi",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "VND",
			Languages:   `["vi"]`,
			CallingCode: "+84",
			FlagEmoji:   "🇻🇳",
			Latitude:    float64Ptr(14.0583),
			Longitude:   float64Ptr(108.2772),
			Active:      true,
		},
		{
			ID:          "MY",
			Name:        "Malaysia",
			NativeName:  "Malaysia",
			Capital:     "Kuala Lumpur",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "MYR",
			Languages:   `["ms"]`,
			CallingCode: "+60",
			FlagEmoji:   "🇲🇾",
			Latitude:    float64Ptr(4.2105),
			Longitude:   float64Ptr(101.9758),
			Active:      true,
		},
		{
			ID:          "MM",
			Name:        "Myanmar",
			NativeName:  "မြန်မာ",
			Capital:     "Naypyidaw",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "MMK",
			Languages:   `["my"]`,
			CallingCode: "+95",
			FlagEmoji:   "🇲🇲",
			Latitude:    float64Ptr(21.9162),
			Longitude:   float64Ptr(95.9560),
			Active:      true,
		},
		{
			ID:          "KH",
			Name:        "Cambodia",
			NativeName:  "កម្ពុជា",
			Capital:     "Phnom Penh",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "KHR",
			Languages:   `["km"]`,
			CallingCode: "+855",
			FlagEmoji:   "🇰🇭",
			Latitude:    float64Ptr(12.5657),
			Longitude:   float64Ptr(104.9910),
			Active:      true,
		},
		{
			ID:          "LA",
			Name:        "Laos",
			NativeName:  "ສປປລາວ",
			Capital:     "Vientiane",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "LAK",
			Languages:   `["lo"]`,
			CallingCode: "+856",
			FlagEmoji:   "🇱🇦",
			Latitude:    float64Ptr(19.8563),
			Longitude:   float64Ptr(102.4955),
			Active:      true,
		},
		{
			ID:          "BN",
			Name:        "Brunei",
			NativeName:  "Brunei Darussalam",
			Capital:     "Bandar Seri Begawan",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "BND",
			Languages:   `["ms"]`,
			CallingCode: "+673",
			FlagEmoji:   "🇧🇳",
			Latitude:    float64Ptr(4.5353),
			Longitude:   float64Ptr(114.7277),
			Active:      true,
		},
		{
			ID:          "TL",
			Name:        "Timor-Leste",
			NativeName:  "Timor-Leste",
			Capital:     "Dili",
			Region:      "Asia",
			Subregion:   "South-Eastern Asia",
			Currency:    "USD",
			Languages:   `["pt","tet"]`,
			CallingCode: "+670",
			FlagEmoji:   "🇹🇱",
			Latitude:    float64Ptr(-8.8742),
			Longitude:   float64Ptr(125.7275),
			Active:      true,
		},
		// East Asian Countries/Regions
		{
			ID:          "TW",
			Name:        "Taiwan",
			NativeName:  "臺灣",
			Capital:     "Taipei",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "TWD",
			Languages:   `["zh"]`,
			CallingCode: "+886",
			FlagEmoji:   "🇹🇼",
			Latitude:    float64Ptr(23.6978),
			Longitude:   float64Ptr(120.9605),
			Active:      true,
		},
		{
			ID:          "HK",
			Name:        "Hong Kong",
			NativeName:  "香港",
			Capital:     "Hong Kong",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "HKD",
			Languages:   `["zh","en"]`,
			CallingCode: "+852",
			FlagEmoji:   "🇭🇰",
			Latitude:    float64Ptr(22.3193),
			Longitude:   float64Ptr(114.1694),
			Active:      true,
		},
		{
			ID:          "MO",
			Name:        "Macau",
			NativeName:  "澳門",
			Capital:     "Macau",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "MOP",
			Languages:   `["zh","pt"]`,
			CallingCode: "+853",
			FlagEmoji:   "🇲🇴",
			Latitude:    float64Ptr(22.1987),
			Longitude:   float64Ptr(113.5439),
			Active:      true,
		},
		{
			ID:          "MN",
			Name:        "Mongolia",
			NativeName:  "Монгол улс",
			Capital:     "Ulaanbaatar",
			Region:      "Asia",
			Subregion:   "Eastern Asia",
			Currency:    "MNT",
			Languages:   `["mn"]`,
			CallingCode: "+976",
			FlagEmoji:   "🇲🇳",
			Latitude:    float64Ptr(46.8625),
			Longitude:   float64Ptr(103.8467),
			Active:      true,
		},
		// Middle East
		{
			ID:          "SA",
			Name:        "Saudi Arabia",
			NativeName:  "المملكة العربية السعودية",
			Capital:     "Riyadh",
			Region:      "Asia",
			Subregion:   "Western Asia",
			Currency:    "SAR",
			Languages:   `["ar"]`,
			CallingCode: "+966",
			FlagEmoji:   "🇸🇦",
			Latitude:    float64Ptr(23.8859),
			Longitude:   float64Ptr(45.0792),
			Active:      true,
		},
		{
			ID:          "QA",
			Name:        "Qatar",
			NativeName:  "قطر",
			Capital:     "Doha",
			Region:      "Asia",
			Subregion:   "Western Asia",
			Currency:    "QAR",
			Languages:   `["ar"]`,
			CallingCode: "+974",
			FlagEmoji:   "🇶🇦",
			Latitude:    float64Ptr(25.3548),
			Longitude:   float64Ptr(51.1839),
			Active:      true,
		},
		{
			ID:          "KW",
			Name:        "Kuwait",
			NativeName:  "الكويت",
			Capital:     "Kuwait City",
			Region:      "Asia",
			Subregion:   "Western Asia",
			Currency:    "KWD",
			Languages:   `["ar"]`,
			CallingCode: "+965",
			FlagEmoji:   "🇰🇼",
			Latitude:    float64Ptr(29.3117),
			Longitude:   float64Ptr(47.4818),
			Active:      true,
		},
		{
			ID:          "BH",
			Name:        "Bahrain",
			NativeName:  "البحرين",
			Capital:     "Manama",
			Region:      "Asia",
			Subregion:   "Western Asia",
			Currency:    "BHD",
			Languages:   `["ar"]`,
			CallingCode: "+973",
			FlagEmoji:   "🇧🇭",
			Latitude:    float64Ptr(26.0667),
			Longitude:   float64Ptr(50.5577),
			Active:      true,
		},
		{
			ID:          "OM",
			Name:        "Oman",
			NativeName:  "عمان",
			Capital:     "Muscat",
			Region:      "Asia",
			Subregion:   "Western Asia",
			Currency:    "OMR",
			Languages:   `["ar"]`,
			CallingCode: "+968",
			FlagEmoji:   "🇴🇲",
			Latitude:    float64Ptr(21.5129),
			Longitude:   float64Ptr(55.9233),
			Active:      true,
		},
		{
			ID:          "IL",
			Name:        "Israel",
			NativeName:  "ישראל",
			Capital:     "Jerusalem",
			Region:      "Asia",
			Subregion:   "Western Asia",
			Currency:    "ILS",
			Languages:   `["he","ar"]`,
			CallingCode: "+972",
			FlagEmoji:   "🇮🇱",
			Latitude:    float64Ptr(31.0461),
			Longitude:   float64Ptr(34.8516),
			Active:      true,
		},
		{
			ID:          "TR",
			Name:        "Turkey",
			NativeName:  "Türkiye",
			Capital:     "Ankara",
			Region:      "Asia",
			Subregion:   "Western Asia",
			Currency:    "TRY",
			Languages:   `["tr"]`,
			CallingCode: "+90",
			FlagEmoji:   "🇹🇷",
			Latitude:    float64Ptr(38.9637),
			Longitude:   float64Ptr(35.2433),
			Active:      true,
		},
		// Additional European Countries
		{
			ID:          "IE",
			Name:        "Ireland",
			NativeName:  "Éire",
			Capital:     "Dublin",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "EUR",
			Languages:   `["en","ga"]`,
			CallingCode: "+353",
			FlagEmoji:   "🇮🇪",
			Latitude:    float64Ptr(53.1424),
			Longitude:   float64Ptr(-7.6921),
			Active:      true,
		},
		{
			ID:          "CH",
			Name:        "Switzerland",
			NativeName:  "Schweiz",
			Capital:     "Bern",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "CHF",
			Languages:   `["de","fr","it","rm"]`,
			CallingCode: "+41",
			FlagEmoji:   "🇨🇭",
			Latitude:    float64Ptr(46.8182),
			Longitude:   float64Ptr(8.2275),
			Active:      true,
		},
		{
			ID:          "AT",
			Name:        "Austria",
			NativeName:  "Österreich",
			Capital:     "Vienna",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "EUR",
			Languages:   `["de"]`,
			CallingCode: "+43",
			FlagEmoji:   "🇦🇹",
			Latitude:    float64Ptr(47.5162),
			Longitude:   float64Ptr(14.5501),
			Active:      true,
		},
		{
			ID:          "BE",
			Name:        "Belgium",
			NativeName:  "België",
			Capital:     "Brussels",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "EUR",
			Languages:   `["nl","fr","de"]`,
			CallingCode: "+32",
			FlagEmoji:   "🇧🇪",
			Latitude:    float64Ptr(50.5039),
			Longitude:   float64Ptr(4.4699),
			Active:      true,
		},
		{
			ID:          "PT",
			Name:        "Portugal",
			NativeName:  "Portugal",
			Capital:     "Lisbon",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "EUR",
			Languages:   `["pt"]`,
			CallingCode: "+351",
			FlagEmoji:   "🇵🇹",
			Latitude:    float64Ptr(39.3999),
			Longitude:   float64Ptr(-8.2245),
			Active:      true,
		},
		{
			ID:          "PL",
			Name:        "Poland",
			NativeName:  "Polska",
			Capital:     "Warsaw",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "PLN",
			Languages:   `["pl"]`,
			CallingCode: "+48",
			FlagEmoji:   "🇵🇱",
			Latitude:    float64Ptr(51.9194),
			Longitude:   float64Ptr(19.1451),
			Active:      true,
		},
		{
			ID:          "NO",
			Name:        "Norway",
			NativeName:  "Norge",
			Capital:     "Oslo",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "NOK",
			Languages:   `["no"]`,
			CallingCode: "+47",
			FlagEmoji:   "🇳🇴",
			Latitude:    float64Ptr(60.4720),
			Longitude:   float64Ptr(8.4689),
			Active:      true,
		},
		{
			ID:          "DK",
			Name:        "Denmark",
			NativeName:  "Danmark",
			Capital:     "Copenhagen",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "DKK",
			Languages:   `["da"]`,
			CallingCode: "+45",
			FlagEmoji:   "🇩🇰",
			Latitude:    float64Ptr(56.2639),
			Longitude:   float64Ptr(9.5018),
			Active:      true,
		},
		{
			ID:          "FI",
			Name:        "Finland",
			NativeName:  "Suomi",
			Capital:     "Helsinki",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "EUR",
			Languages:   `["fi","sv"]`,
			CallingCode: "+358",
			FlagEmoji:   "🇫🇮",
			Latitude:    float64Ptr(61.9241),
			Longitude:   float64Ptr(25.7482),
			Active:      true,
		},
		{
			ID:          "RU",
			Name:        "Russia",
			NativeName:  "Россия",
			Capital:     "Moscow",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "RUB",
			Languages:   `["ru"]`,
			CallingCode: "+7",
			FlagEmoji:   "🇷🇺",
			Latitude:    float64Ptr(61.5240),
			Longitude:   float64Ptr(105.3188),
			Active:      true,
		},
		// Additional Americas
		{
			ID:          "AR",
			Name:        "Argentina",
			NativeName:  "Argentina",
			Capital:     "Buenos Aires",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "ARS",
			Languages:   `["es"]`,
			CallingCode: "+54",
			FlagEmoji:   "🇦🇷",
			Latitude:    float64Ptr(-38.4161),
			Longitude:   float64Ptr(-63.6167),
			Active:      true,
		},
		{
			ID:          "CL",
			Name:        "Chile",
			NativeName:  "Chile",
			Capital:     "Santiago",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "CLP",
			Languages:   `["es"]`,
			CallingCode: "+56",
			FlagEmoji:   "🇨🇱",
			Latitude:    float64Ptr(-35.6751),
			Longitude:   float64Ptr(-71.5430),
			Active:      true,
		},
		{
			ID:          "CO",
			Name:        "Colombia",
			NativeName:  "Colombia",
			Capital:     "Bogotá",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "COP",
			Languages:   `["es"]`,
			CallingCode: "+57",
			FlagEmoji:   "🇨🇴",
			Latitude:    float64Ptr(4.5709),
			Longitude:   float64Ptr(-74.2973),
			Active:      true,
		},
		{
			ID:          "PE",
			Name:        "Peru",
			NativeName:  "Perú",
			Capital:     "Lima",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "PEN",
			Languages:   `["es"]`,
			CallingCode: "+51",
			FlagEmoji:   "🇵🇪",
			Latitude:    float64Ptr(-9.1900),
			Longitude:   float64Ptr(-75.0152),
			Active:      true,
		},
		// Africa
		{
			ID:          "EG",
			Name:        "Egypt",
			NativeName:  "مصر",
			Capital:     "Cairo",
			Region:      "Africa",
			Subregion:   "Northern Africa",
			Currency:    "EGP",
			Languages:   `["ar"]`,
			CallingCode: "+20",
			FlagEmoji:   "🇪🇬",
			Latitude:    float64Ptr(26.8206),
			Longitude:   float64Ptr(30.8025),
			Active:      true,
		},
		{
			ID:          "NG",
			Name:        "Nigeria",
			NativeName:  "Nigeria",
			Capital:     "Abuja",
			Region:      "Africa",
			Subregion:   "Western Africa",
			Currency:    "NGN",
			Languages:   `["en"]`,
			CallingCode: "+234",
			FlagEmoji:   "🇳🇬",
			Latitude:    float64Ptr(9.0820),
			Longitude:   float64Ptr(8.6753),
			Active:      true,
		},
		{
			ID:          "KE",
			Name:        "Kenya",
			NativeName:  "Kenya",
			Capital:     "Nairobi",
			Region:      "Africa",
			Subregion:   "Eastern Africa",
			Currency:    "KES",
			Languages:   `["en","sw"]`,
			CallingCode: "+254",
			FlagEmoji:   "🇰🇪",
			Latitude:    float64Ptr(-0.0236),
			Longitude:   float64Ptr(37.9062),
			Active:      true,
		},
		{
			ID:          "GH",
			Name:        "Ghana",
			NativeName:  "Ghana",
			Capital:     "Accra",
			Region:      "Africa",
			Subregion:   "Western Africa",
			Currency:    "GHS",
			Languages:   `["en"]`,
			CallingCode: "+233",
			FlagEmoji:   "🇬🇭",
			Latitude:    float64Ptr(7.9465),
			Longitude:   float64Ptr(-1.0232),
			Active:      true,
		},
		{
			ID:          "MA",
			Name:        "Morocco",
			NativeName:  "المغرب",
			Capital:     "Rabat",
			Region:      "Africa",
			Subregion:   "Northern Africa",
			Currency:    "MAD",
			Languages:   `["ar","ber"]`,
			CallingCode: "+212",
			FlagEmoji:   "🇲🇦",
			Latitude:    float64Ptr(31.7917),
			Longitude:   float64Ptr(-7.0926),
			Active:      true,
		},
		// Additional European Countries
		{
			ID:          "GR",
			Name:        "Greece",
			NativeName:  "Ελλάδα",
			Capital:     "Athens",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "EUR",
			Languages:   `["el"]`,
			CallingCode: "+30",
			FlagEmoji:   "🇬🇷",
			Latitude:    float64Ptr(39.0742),
			Longitude:   float64Ptr(21.8243),
			Active:      true,
		},
		{
			ID:          "CZ",
			Name:        "Czech Republic",
			NativeName:  "Česká republika",
			Capital:     "Prague",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "CZK",
			Languages:   `["cs"]`,
			CallingCode: "+420",
			FlagEmoji:   "🇨🇿",
			Latitude:    float64Ptr(49.8175),
			Longitude:   float64Ptr(15.4730),
			Active:      true,
		},
		{
			ID:          "HU",
			Name:        "Hungary",
			NativeName:  "Magyarország",
			Capital:     "Budapest",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "HUF",
			Languages:   `["hu"]`,
			CallingCode: "+36",
			FlagEmoji:   "🇭🇺",
			Latitude:    float64Ptr(47.1625),
			Longitude:   float64Ptr(19.5033),
			Active:      true,
		},
		{
			ID:          "RO",
			Name:        "Romania",
			NativeName:  "România",
			Capital:     "Bucharest",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "RON",
			Languages:   `["ro"]`,
			CallingCode: "+40",
			FlagEmoji:   "🇷🇴",
			Latitude:    float64Ptr(45.9432),
			Longitude:   float64Ptr(24.9668),
			Active:      true,
		},
		{
			ID:          "UA",
			Name:        "Ukraine",
			NativeName:  "Україна",
			Capital:     "Kyiv",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "UAH",
			Languages:   `["uk"]`,
			CallingCode: "+380",
			FlagEmoji:   "🇺🇦",
			Latitude:    float64Ptr(48.3794),
			Longitude:   float64Ptr(31.1656),
			Active:      true,
		},
		{
			ID:          "HR",
			Name:        "Croatia",
			NativeName:  "Hrvatska",
			Capital:     "Zagreb",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "EUR",
			Languages:   `["hr"]`,
			CallingCode: "+385",
			FlagEmoji:   "🇭🇷",
			Latitude:    float64Ptr(45.1000),
			Longitude:   float64Ptr(15.2000),
			Active:      true,
		},
		{
			ID:          "SK",
			Name:        "Slovakia",
			NativeName:  "Slovensko",
			Capital:     "Bratislava",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "EUR",
			Languages:   `["sk"]`,
			CallingCode: "+421",
			FlagEmoji:   "🇸🇰",
			Latitude:    float64Ptr(48.6690),
			Longitude:   float64Ptr(19.6990),
			Active:      true,
		},
		{
			ID:          "SI",
			Name:        "Slovenia",
			NativeName:  "Slovenija",
			Capital:     "Ljubljana",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "EUR",
			Languages:   `["sl"]`,
			CallingCode: "+386",
			FlagEmoji:   "🇸🇮",
			Latitude:    float64Ptr(46.1512),
			Longitude:   float64Ptr(14.9955),
			Active:      true,
		},
		{
			ID:          "BG",
			Name:        "Bulgaria",
			NativeName:  "България",
			Capital:     "Sofia",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "BGN",
			Languages:   `["bg"]`,
			CallingCode: "+359",
			FlagEmoji:   "🇧🇬",
			Latitude:    float64Ptr(42.7339),
			Longitude:   float64Ptr(25.4858),
			Active:      true,
		},
		{
			ID:          "LT",
			Name:        "Lithuania",
			NativeName:  "Lietuva",
			Capital:     "Vilnius",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "EUR",
			Languages:   `["lt"]`,
			CallingCode: "+370",
			FlagEmoji:   "🇱🇹",
			Latitude:    float64Ptr(55.1694),
			Longitude:   float64Ptr(23.8813),
			Active:      true,
		},
		{
			ID:          "LV",
			Name:        "Latvia",
			NativeName:  "Latvija",
			Capital:     "Riga",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "EUR",
			Languages:   `["lv"]`,
			CallingCode: "+371",
			FlagEmoji:   "🇱🇻",
			Latitude:    float64Ptr(56.8796),
			Longitude:   float64Ptr(24.6032),
			Active:      true,
		},
		{
			ID:          "EE",
			Name:        "Estonia",
			NativeName:  "Eesti",
			Capital:     "Tallinn",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "EUR",
			Languages:   `["et"]`,
			CallingCode: "+372",
			FlagEmoji:   "🇪🇪",
			Latitude:    float64Ptr(58.5953),
			Longitude:   float64Ptr(25.0136),
			Active:      true,
		},
		{
			ID:          "LU",
			Name:        "Luxembourg",
			NativeName:  "Luxembourg",
			Capital:     "Luxembourg",
			Region:      "Europe",
			Subregion:   "Western Europe",
			Currency:    "EUR",
			Languages:   `["lb","de","fr"]`,
			CallingCode: "+352",
			FlagEmoji:   "🇱🇺",
			Latitude:    float64Ptr(49.8153),
			Longitude:   float64Ptr(6.1296),
			Active:      true,
		},
		{
			ID:          "IS",
			Name:        "Iceland",
			NativeName:  "Ísland",
			Capital:     "Reykjavik",
			Region:      "Europe",
			Subregion:   "Northern Europe",
			Currency:    "ISK",
			Languages:   `["is"]`,
			CallingCode: "+354",
			FlagEmoji:   "🇮🇸",
			Latitude:    float64Ptr(64.9631),
			Longitude:   float64Ptr(-19.0208),
			Active:      true,
		},
		{
			ID:          "RS",
			Name:        "Serbia",
			NativeName:  "Србија",
			Capital:     "Belgrade",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "RSD",
			Languages:   `["sr"]`,
			CallingCode: "+381",
			FlagEmoji:   "🇷🇸",
			Latitude:    float64Ptr(44.0165),
			Longitude:   float64Ptr(21.0059),
			Active:      true,
		},
		{
			ID:          "BA",
			Name:        "Bosnia and Herzegovina",
			NativeName:  "Bosna i Hercegovina",
			Capital:     "Sarajevo",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "BAM",
			Languages:   `["bs","hr","sr"]`,
			CallingCode: "+387",
			FlagEmoji:   "🇧🇦",
			Latitude:    float64Ptr(43.9159),
			Longitude:   float64Ptr(17.6791),
			Active:      true,
		},
		{
			ID:          "ME",
			Name:        "Montenegro",
			NativeName:  "Crna Gora",
			Capital:     "Podgorica",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "EUR",
			Languages:   `["sr"]`,
			CallingCode: "+382",
			FlagEmoji:   "🇲🇪",
			Latitude:    float64Ptr(42.7087),
			Longitude:   float64Ptr(19.3744),
			Active:      true,
		},
		{
			ID:          "MK",
			Name:        "North Macedonia",
			NativeName:  "Северна Македонија",
			Capital:     "Skopje",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "MKD",
			Languages:   `["mk"]`,
			CallingCode: "+389",
			FlagEmoji:   "🇲🇰",
			Latitude:    float64Ptr(41.5124),
			Longitude:   float64Ptr(21.7453),
			Active:      true,
		},
		{
			ID:          "AL",
			Name:        "Albania",
			NativeName:  "Shqipëria",
			Capital:     "Tirana",
			Region:      "Europe",
			Subregion:   "Southern Europe",
			Currency:    "ALL",
			Languages:   `["sq"]`,
			CallingCode: "+355",
			FlagEmoji:   "🇦🇱",
			Latitude:    float64Ptr(41.1533),
			Longitude:   float64Ptr(20.1683),
			Active:      true,
		},
		{
			ID:          "MD",
			Name:        "Moldova",
			NativeName:  "Moldova",
			Capital:     "Chișinău",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "MDL",
			Languages:   `["ro"]`,
			CallingCode: "+373",
			FlagEmoji:   "🇲🇩",
			Latitude:    float64Ptr(47.4116),
			Longitude:   float64Ptr(28.3699),
			Active:      true,
		},
		{
			ID:          "BY",
			Name:        "Belarus",
			NativeName:  "Беларусь",
			Capital:     "Minsk",
			Region:      "Europe",
			Subregion:   "Eastern Europe",
			Currency:    "BYN",
			Languages:   `["be","ru"]`,
			CallingCode: "+375",
			FlagEmoji:   "🇧🇾",
			Latitude:    float64Ptr(53.7098),
			Longitude:   float64Ptr(27.9534),
			Active:      true,
		},
		// Central America and Caribbean
		{
			ID:          "PA",
			Name:        "Panama",
			NativeName:  "Panamá",
			Capital:     "Panama City",
			Region:      "Americas",
			Subregion:   "Central America",
			Currency:    "PAB",
			Languages:   `["es"]`,
			CallingCode: "+507",
			FlagEmoji:   "🇵🇦",
			Latitude:    float64Ptr(8.5380),
			Longitude:   float64Ptr(-80.7821),
			Active:      true,
		},
		{
			ID:          "CR",
			Name:        "Costa Rica",
			NativeName:  "Costa Rica",
			Capital:     "San José",
			Region:      "Americas",
			Subregion:   "Central America",
			Currency:    "CRC",
			Languages:   `["es"]`,
			CallingCode: "+506",
			FlagEmoji:   "🇨🇷",
			Latitude:    float64Ptr(9.7489),
			Longitude:   float64Ptr(-83.7534),
			Active:      true,
		},
		{
			ID:          "GT",
			Name:        "Guatemala",
			NativeName:  "Guatemala",
			Capital:     "Guatemala City",
			Region:      "Americas",
			Subregion:   "Central America",
			Currency:    "GTQ",
			Languages:   `["es"]`,
			CallingCode: "+502",
			FlagEmoji:   "🇬🇹",
			Latitude:    float64Ptr(15.7835),
			Longitude:   float64Ptr(-90.2308),
			Active:      true,
		},
		{
			ID:          "HN",
			Name:        "Honduras",
			NativeName:  "Honduras",
			Capital:     "Tegucigalpa",
			Region:      "Americas",
			Subregion:   "Central America",
			Currency:    "HNL",
			Languages:   `["es"]`,
			CallingCode: "+504",
			FlagEmoji:   "🇭🇳",
			Latitude:    float64Ptr(15.1990),
			Longitude:   float64Ptr(-86.2419),
			Active:      true,
		},
		{
			ID:          "SV",
			Name:        "El Salvador",
			NativeName:  "El Salvador",
			Capital:     "San Salvador",
			Region:      "Americas",
			Subregion:   "Central America",
			Currency:    "USD",
			Languages:   `["es"]`,
			CallingCode: "+503",
			FlagEmoji:   "🇸🇻",
			Latitude:    float64Ptr(13.7942),
			Longitude:   float64Ptr(-88.8965),
			Active:      true,
		},
		{
			ID:          "NI",
			Name:        "Nicaragua",
			NativeName:  "Nicaragua",
			Capital:     "Managua",
			Region:      "Americas",
			Subregion:   "Central America",
			Currency:    "NIO",
			Languages:   `["es"]`,
			CallingCode: "+505",
			FlagEmoji:   "🇳🇮",
			Latitude:    float64Ptr(12.8654),
			Longitude:   float64Ptr(-85.2072),
			Active:      true,
		},
		{
			ID:          "BZ",
			Name:        "Belize",
			NativeName:  "Belize",
			Capital:     "Belmopan",
			Region:      "Americas",
			Subregion:   "Central America",
			Currency:    "BZD",
			Languages:   `["en","es"]`,
			CallingCode: "+501",
			FlagEmoji:   "🇧🇿",
			Latitude:    float64Ptr(17.1899),
			Longitude:   float64Ptr(-88.4976),
			Active:      true,
		},
		{
			ID:          "CU",
			Name:        "Cuba",
			NativeName:  "Cuba",
			Capital:     "Havana",
			Region:      "Americas",
			Subregion:   "Caribbean",
			Currency:    "CUP",
			Languages:   `["es"]`,
			CallingCode: "+53",
			FlagEmoji:   "🇨🇺",
			Latitude:    float64Ptr(21.5218),
			Longitude:   float64Ptr(-77.7812),
			Active:      true,
		},
		{
			ID:          "DO",
			Name:        "Dominican Republic",
			NativeName:  "República Dominicana",
			Capital:     "Santo Domingo",
			Region:      "Americas",
			Subregion:   "Caribbean",
			Currency:    "DOP",
			Languages:   `["es"]`,
			CallingCode: "+1",
			FlagEmoji:   "🇩🇴",
			Latitude:    float64Ptr(18.7357),
			Longitude:   float64Ptr(-70.1627),
			Active:      true,
		},
		{
			ID:          "JM",
			Name:        "Jamaica",
			NativeName:  "Jamaica",
			Capital:     "Kingston",
			Region:      "Americas",
			Subregion:   "Caribbean",
			Currency:    "JMD",
			Languages:   `["en"]`,
			CallingCode: "+1",
			FlagEmoji:   "🇯🇲",
			Latitude:    float64Ptr(18.1096),
			Longitude:   float64Ptr(-77.2975),
			Active:      true,
		},
		{
			ID:          "HT",
			Name:        "Haiti",
			NativeName:  "Haïti",
			Capital:     "Port-au-Prince",
			Region:      "Americas",
			Subregion:   "Caribbean",
			Currency:    "HTG",
			Languages:   `["fr","ht"]`,
			CallingCode: "+509",
			FlagEmoji:   "🇭🇹",
			Latitude:    float64Ptr(18.9712),
			Longitude:   float64Ptr(-72.2852),
			Active:      true,
		},
		{
			ID:          "TT",
			Name:        "Trinidad and Tobago",
			NativeName:  "Trinidad and Tobago",
			Capital:     "Port of Spain",
			Region:      "Americas",
			Subregion:   "Caribbean",
			Currency:    "TTD",
			Languages:   `["en"]`,
			CallingCode: "+1",
			FlagEmoji:   "🇹🇹",
			Latitude:    float64Ptr(10.6918),
			Longitude:   float64Ptr(-61.2225),
			Active:      true,
		},
		{
			ID:          "PR",
			Name:        "Puerto Rico",
			NativeName:  "Puerto Rico",
			Capital:     "San Juan",
			Region:      "Americas",
			Subregion:   "Caribbean",
			Currency:    "USD",
			Languages:   `["es","en"]`,
			CallingCode: "+1",
			FlagEmoji:   "🇵🇷",
			Latitude:    float64Ptr(18.2208),
			Longitude:   float64Ptr(-66.5901),
			Active:      true,
		},
		// Additional South American Countries
		{
			ID:          "VE",
			Name:        "Venezuela",
			NativeName:  "Venezuela",
			Capital:     "Caracas",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "VES",
			Languages:   `["es"]`,
			CallingCode: "+58",
			FlagEmoji:   "🇻🇪",
			Latitude:    float64Ptr(6.4238),
			Longitude:   float64Ptr(-66.5897),
			Active:      true,
		},
		{
			ID:          "EC",
			Name:        "Ecuador",
			NativeName:  "Ecuador",
			Capital:     "Quito",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "USD",
			Languages:   `["es"]`,
			CallingCode: "+593",
			FlagEmoji:   "🇪🇨",
			Latitude:    float64Ptr(-1.8312),
			Longitude:   float64Ptr(-78.1834),
			Active:      true,
		},
		{
			ID:          "BO",
			Name:        "Bolivia",
			NativeName:  "Bolivia",
			Capital:     "Sucre",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "BOB",
			Languages:   `["es","qu","ay"]`,
			CallingCode: "+591",
			FlagEmoji:   "🇧🇴",
			Latitude:    float64Ptr(-16.2902),
			Longitude:   float64Ptr(-63.5887),
			Active:      true,
		},
		{
			ID:          "PY",
			Name:        "Paraguay",
			NativeName:  "Paraguay",
			Capital:     "Asunción",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "PYG",
			Languages:   `["es","gn"]`,
			CallingCode: "+595",
			FlagEmoji:   "🇵🇾",
			Latitude:    float64Ptr(-23.4425),
			Longitude:   float64Ptr(-58.4438),
			Active:      true,
		},
		{
			ID:          "UY",
			Name:        "Uruguay",
			NativeName:  "Uruguay",
			Capital:     "Montevideo",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "UYU",
			Languages:   `["es"]`,
			CallingCode: "+598",
			FlagEmoji:   "🇺🇾",
			Latitude:    float64Ptr(-32.5228),
			Longitude:   float64Ptr(-55.7658),
			Active:      true,
		},
		{
			ID:          "GY",
			Name:        "Guyana",
			NativeName:  "Guyana",
			Capital:     "Georgetown",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "GYD",
			Languages:   `["en"]`,
			CallingCode: "+592",
			FlagEmoji:   "🇬🇾",
			Latitude:    float64Ptr(4.8604),
			Longitude:   float64Ptr(-58.9302),
			Active:      true,
		},
		{
			ID:          "SR",
			Name:        "Suriname",
			NativeName:  "Suriname",
			Capital:     "Paramaribo",
			Region:      "Americas",
			Subregion:   "South America",
			Currency:    "SRD",
			Languages:   `["nl"]`,
			CallingCode: "+597",
			FlagEmoji:   "🇸🇷",
			Latitude:    float64Ptr(3.9193),
			Longitude:   float64Ptr(-56.0278),
			Active:      true,
		},
		// Additional African Countries
		{
			ID:          "TZ",
			Name:        "Tanzania",
			NativeName:  "Tanzania",
			Capital:     "Dodoma",
			Region:      "Africa",
			Subregion:   "Eastern Africa",
			Currency:    "TZS",
			Languages:   `["sw","en"]`,
			CallingCode: "+255",
			FlagEmoji:   "🇹🇿",
			Latitude:    float64Ptr(-6.3690),
			Longitude:   float64Ptr(34.8888),
			Active:      true,
		},
		{
			ID:          "ET",
			Name:        "Ethiopia",
			NativeName:  "ኢትዮጵያ",
			Capital:     "Addis Ababa",
			Region:      "Africa",
			Subregion:   "Eastern Africa",
			Currency:    "ETB",
			Languages:   `["am"]`,
			CallingCode: "+251",
			FlagEmoji:   "🇪🇹",
			Latitude:    float64Ptr(9.1450),
			Longitude:   float64Ptr(40.4897),
			Active:      true,
		},
		{
			ID:          "UG",
			Name:        "Uganda",
			NativeName:  "Uganda",
			Capital:     "Kampala",
			Region:      "Africa",
			Subregion:   "Eastern Africa",
			Currency:    "UGX",
			Languages:   `["en","sw"]`,
			CallingCode: "+256",
			FlagEmoji:   "🇺🇬",
			Latitude:    float64Ptr(1.3733),
			Longitude:   float64Ptr(32.2903),
			Active:      true,
		},
		{
			ID:          "RW",
			Name:        "Rwanda",
			NativeName:  "Rwanda",
			Capital:     "Kigali",
			Region:      "Africa",
			Subregion:   "Eastern Africa",
			Currency:    "RWF",
			Languages:   `["rw","en","fr"]`,
			CallingCode: "+250",
			FlagEmoji:   "🇷🇼",
			Latitude:    float64Ptr(-1.9403),
			Longitude:   float64Ptr(29.8739),
			Active:      true,
		},
		{
			ID:          "DZ",
			Name:        "Algeria",
			NativeName:  "الجزائر",
			Capital:     "Algiers",
			Region:      "Africa",
			Subregion:   "Northern Africa",
			Currency:    "DZD",
			Languages:   `["ar"]`,
			CallingCode: "+213",
			FlagEmoji:   "🇩🇿",
			Latitude:    float64Ptr(28.0339),
			Longitude:   float64Ptr(1.6596),
			Active:      true,
		},
		{
			ID:          "TN",
			Name:        "Tunisia",
			NativeName:  "تونس",
			Capital:     "Tunis",
			Region:      "Africa",
			Subregion:   "Northern Africa",
			Currency:    "TND",
			Languages:   `["ar"]`,
			CallingCode: "+216",
			FlagEmoji:   "🇹🇳",
			Latitude:    float64Ptr(33.8869),
			Longitude:   float64Ptr(9.5375),
			Active:      true,
		},
		{
			ID:          "LY",
			Name:        "Libya",
			NativeName:  "ليبيا",
			Capital:     "Tripoli",
			Region:      "Africa",
			Subregion:   "Northern Africa",
			Currency:    "LYD",
			Languages:   `["ar"]`,
			CallingCode: "+218",
			FlagEmoji:   "🇱🇾",
			Latitude:    float64Ptr(26.3351),
			Longitude:   float64Ptr(17.2283),
			Active:      true,
		},
		{
			ID:          "SD",
			Name:        "Sudan",
			NativeName:  "السودان",
			Capital:     "Khartoum",
			Region:      "Africa",
			Subregion:   "Northern Africa",
			Currency:    "SDG",
			Languages:   `["ar","en"]`,
			CallingCode: "+249",
			FlagEmoji:   "🇸🇩",
			Latitude:    float64Ptr(12.8628),
			Longitude:   float64Ptr(30.2176),
			Active:      true,
		},
		{
			ID:          "AO",
			Name:        "Angola",
			NativeName:  "Angola",
			Capital:     "Luanda",
			Region:      "Africa",
			Subregion:   "Middle Africa",
			Currency:    "AOA",
			Languages:   `["pt"]`,
			CallingCode: "+244",
			FlagEmoji:   "🇦🇴",
			Latitude:    float64Ptr(-11.2027),
			Longitude:   float64Ptr(17.8739),
			Active:      true,
		},
		{
			ID:          "MZ",
			Name:        "Mozambique",
			NativeName:  "Moçambique",
			Capital:     "Maputo",
			Region:      "Africa",
			Subregion:   "Eastern Africa",
			Currency:    "MZN",
			Languages:   `["pt"]`,
			CallingCode: "+258",
			FlagEmoji:   "🇲🇿",
			Latitude:    float64Ptr(-18.6657),
			Longitude:   float64Ptr(35.5296),
			Active:      true,
		},
		{
			ID:          "ZW",
			Name:        "Zimbabwe",
			NativeName:  "Zimbabwe",
			Capital:     "Harare",
			Region:      "Africa",
			Subregion:   "Eastern Africa",
			Currency:    "ZWL",
			Languages:   `["en","sn","nd"]`,
			CallingCode: "+263",
			FlagEmoji:   "🇿🇼",
			Latitude:    float64Ptr(-19.0154),
			Longitude:   float64Ptr(29.1549),
			Active:      true,
		},
		{
			ID:          "ZM",
			Name:        "Zambia",
			NativeName:  "Zambia",
			Capital:     "Lusaka",
			Region:      "Africa",
			Subregion:   "Eastern Africa",
			Currency:    "ZMW",
			Languages:   `["en"]`,
			CallingCode: "+260",
			FlagEmoji:   "🇿🇲",
			Latitude:    float64Ptr(-13.1339),
			Longitude:   float64Ptr(27.8493),
			Active:      true,
		},
		{
			ID:          "BW",
			Name:        "Botswana",
			NativeName:  "Botswana",
			Capital:     "Gaborone",
			Region:      "Africa",
			Subregion:   "Southern Africa",
			Currency:    "BWP",
			Languages:   `["en","tn"]`,
			CallingCode: "+267",
			FlagEmoji:   "🇧🇼",
			Latitude:    float64Ptr(-22.3285),
			Longitude:   float64Ptr(24.6849),
			Active:      true,
		},
		{
			ID:          "NA",
			Name:        "Namibia",
			NativeName:  "Namibia",
			Capital:     "Windhoek",
			Region:      "Africa",
			Subregion:   "Southern Africa",
			Currency:    "NAD",
			Languages:   `["en","af"]`,
			CallingCode: "+264",
			FlagEmoji:   "🇳🇦",
			Latitude:    float64Ptr(-22.9576),
			Longitude:   float64Ptr(18.4904),
			Active:      true,
		},
		{
			ID:          "SN",
			Name:        "Senegal",
			NativeName:  "Sénégal",
			Capital:     "Dakar",
			Region:      "Africa",
			Subregion:   "Western Africa",
			Currency:    "XOF",
			Languages:   `["fr"]`,
			CallingCode: "+221",
			FlagEmoji:   "🇸🇳",
			Latitude:    float64Ptr(14.4974),
			Longitude:   float64Ptr(-14.4524),
			Active:      true,
		},
		{
			ID:          "CI",
			Name:        "Ivory Coast",
			NativeName:  "Côte d'Ivoire",
			Capital:     "Yamoussoukro",
			Region:      "Africa",
			Subregion:   "Western Africa",
			Currency:    "XOF",
			Languages:   `["fr"]`,
			CallingCode: "+225",
			FlagEmoji:   "🇨🇮",
			Latitude:    float64Ptr(7.5400),
			Longitude:   float64Ptr(-5.5471),
			Active:      true,
		},
		{
			ID:          "CM",
			Name:        "Cameroon",
			NativeName:  "Cameroun",
			Capital:     "Yaoundé",
			Region:      "Africa",
			Subregion:   "Middle Africa",
			Currency:    "XAF",
			Languages:   `["fr","en"]`,
			CallingCode: "+237",
			FlagEmoji:   "🇨🇲",
			Latitude:    float64Ptr(7.3697),
			Longitude:   float64Ptr(12.3547),
			Active:      true,
		},
		// Oceania
		{
			ID:          "FJ",
			Name:        "Fiji",
			NativeName:  "Fiji",
			Capital:     "Suva",
			Region:      "Oceania",
			Subregion:   "Melanesia",
			Currency:    "FJD",
			Languages:   `["en","fj","hi"]`,
			CallingCode: "+679",
			FlagEmoji:   "🇫🇯",
			Latitude:    float64Ptr(-17.7134),
			Longitude:   float64Ptr(178.0650),
			Active:      true,
		},
		{
			ID:          "PG",
			Name:        "Papua New Guinea",
			NativeName:  "Papua New Guinea",
			Capital:     "Port Moresby",
			Region:      "Oceania",
			Subregion:   "Melanesia",
			Currency:    "PGK",
			Languages:   `["en","ho","tpi"]`,
			CallingCode: "+675",
			FlagEmoji:   "🇵🇬",
			Latitude:    float64Ptr(-6.3150),
			Longitude:   float64Ptr(143.9555),
			Active:      true,
		},
	}
}
